name: Eva Lacy
description: Technology and Politics
meta_description: "Eva Lacy, Technology and Politics"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://www.lacy.ie'
google_analytics: 'UA-66109085-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://www.lacy.ie'
author:         'Eva Lacy'
